logging:
  config: classpath:logback.xml

camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://localhost:61616

app:
  queue-name:
    memberInteractionsQueue
  relay-rest:
    connection-timeout: 60s
    receive-timeout: 60s

