logging:
  config: classpath:logback.xml

camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://localhost:61616

app:
  subscriber:
    queue-name:
      memberInteractionsQueue
  cxfrs:
    scheme: http
    host: localhost
    port: 9090
    context-path: est2coda
    uri-suffix: memberInteractionsQueue
  tracing:
    tracing-type: none

management:
  endpoint:
    jolokia:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
