logging:
  config: classpath:logback.xml

camel:
  springboot:
    main-run-controller: true

spring:
  activemq:
    broker-url: tcp://localhost:61616

app:
  dispatcher:
    queue-name: memberInteractionsQueue
  relay-rest:
    base: http://localhost:9090/estcoda/
    username: alex
    password: pass
    uri-suffix: memberInteractionsQueue
    connection-timeout: 60s
    receive-timeout: 60s
  tracing:
    tracing-type: zipkin
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
      service-name: ixn-subscriber
      rate: 1.0f
      include-message-body-streams: true

management:
  endpoint:
    jolokia:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
